### ISSUE TITLE
Expose Octave builds

### ISSUE THREAD

**Issue by joshmoore** [ome/ome-release#177]
User reported not being able to find the Octave download. (Mentioned by @carandraug on #ome)
- [x] Need link to appropriate logo for new buttons
- [x] text around supported versions of Octave, etc.

See also:
- https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=7530

**Comment by hflynn** [comment]
A docs page linked from https://www.openmicroscopy.org/site/support/bio-formats5/users/index.html would also be needed.
(For information, I checked download stats and we are currently sitting at 12 total, 7 of which were Sept 2015).

**Comment by carandraug** [comment]
Here's the last email exchange:

Francisco S. wrote:

> Carnë Draug wrote:
> 
> > [...]
> > On a separate note, why did you choose to contact me instead of bioformats
> > developers about this issue?
> 
> [...]
> And to answer your question, the reason why I contacted you and not the developers is because apparently you are the only person on Earth mentioning that there is a bioformats version for octave. It is not written anywhere and even there are versions for octave since 5.1.4, they are not listed.

He's referring to the announcement I made on the Octave mailing list [back in September](https://lists.gnu.org/archive/html/help-octave/2015-09/msg00136.html) which explains why 7 accesses were done in that month.

hflyinn wrote:

> (For information, I checked download stats and we are currently sitting at 12 total, 7 of which were Sept 2015).

This also tells me that the docs would really be needed. This is the third time someone contacts me with issues, so at least 3/12 people have problems installing and making it work.

**Comment by hflynn** [comment]
Hi @carandraug for the download button, what is your preferred text - Octave package? Octave toolbox? Something else?

**Comment by carandraug** [comment]
Octave package is the preferred term.

**Comment by hflynn** [comment]
Thanks!

**Comment by sbesson** [comment]
@carandraug: on the docs front, would you feel like opening a Octave documentation PR or minimally provide the content for @hflynn? Giving a better exposition to the existing Octave packages would certainly have some value for the community. It would be interesting to hear your thoughts on how to get some testing mechanism and  feedback to the development team especially prior to releases.

**Comment by carandraug** [comment]
> @carandraug: on the docs front, would you feel like opening a Octave documentation PR or minimally provide the content for @hflynn? Giving a better exposition to the existing Octave packages would certainly have some value for the community.

Done.

> It would be interesting to hear your thoughts on how to get some testing mechanism and feedback to the development team especially prior to releases.

In an ideal world, Octave would be 100% Matlab compatible and you would be able to use your Matlab test units.  However, it is not, and your tests make use of classdef which hasn't been fully implemented in Octave yet. So your current choices are:
1. change your Matlab tests so they run both in Octave and Matlab;
2. write new tests for Octave (Octave has native support for test units which are usually `%!` blocks at the end of the m files);
3. wait until Octave's classdef implementation is good enough to run your Matlab tests;
4. never test for Octave and blame any issue on Octave's lack of Matlab compatibility.

I can help you if you decide to go via creating Octave native tests. However, I'd guess the duplication of work is not worth it and that instead you should wait that Octave finishes implementing classdef so you can reuse your Matlab tests.

**Comment by sbesson** [comment]
Many thanks for the doc PR. On the testing front, as you suggest 1 and 2 are certainly costly especially given other priorities and knowing that 3 is on the pipeline. Do you have a timeline/roadmap for this? On the other hand, 4. is certainly not the most appropriate way to create a positive interaction between the communities.

As proposed in https://github.com/openmicroscopy/bioformats/pull/2200#issuecomment-173881244, having a Dockerfile shipping the correct prerequisites might be be the first step towards a low-cost way to have some minimal testing of the GNU Octave package prior to releases.

**Comment by carandraug** [comment]
> Many thanks for the doc PR. On the testing front, as you suggest 1 and 2 are certainly costly especially given other priorities and knowing that 3 is on the pipeline. Do you have a timeline/roadmap for this?

In short, no.

A more complete story is that Octave development has no official roadmap. For the specific case of classdef, I believe most of the work was paid. It's a pretty complex piece of work, and Matlab's documentation is far from complete and often completely incorrect. It will require a lot of work that only a handful of people can do. It doesn't look promising.

On the other hand, all it takes is the right person to get a $job to do it, and then it would be quick. There's been a surge of new users and developers (apparent) so the chances of that happening is increasing. But many people need Octave to run legacy Matlab code, and classdef is still pretty recent, not required by the vast majority of users.

Finally, Maybe you don't need a complete implementation of classdef for you test unit? There is a page on the Octave wiki that discusses [its current state](http://wiki.octave.org/Classdef).

**Comment by carandraug** [comment]
The first item mentioned logo for a button. For reference, the correct Octave logo is http://hg.savannah.gnu.org/hgweb/octave/file/default/etc/icons/octave-logo.svg

**Comment by sbesson** [comment]
@carandraug: a logo button was added as part of https://github.com/openmicroscopy/ome-release/pull/178. Together with the documentation (thanks again for this), the downloads page should be modified to increase the visibility of the package as part  the upcoming Bio-Formats 5.1.8 release.

**Comment by carandraug** [comment]
Ah, I see. I didn't realize that it was already done somewhere else.

**Comment by hflynn** [comment]
ome-release PRs merged - Octave package will be available on the download page for Bio-Formats 5.1.8 next week and the upcoming 5.2 releases. Closing this issue.
